job:
  image: hmctspublic.azurecr.io/payment/jobs:latest
  schedule: "0 0,30 14,15,16 10,11,12,13 * ? *"
  environment:
    REPORT_NAME: bar-csv-report
global:
  environment: aat
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  enableKeyVaults: true
  job:
    kind: Job