job:
  image: hmctspublic.azurecr.io/payment/jobs:pr-17
  schedule: "0 30,0 12/12,15/12,16/12 * * ?"
  environment:
    REPORT_NAME: pba-csv-report
global:
  environment: aat
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  enableKeyVaults: true
  job:
    kind: Job